FROM hiakki/php-fpm_on_alpine
ADD VERSION .
MAINTAINER Akshay Gupta
LABEL maintainer="hy.akshay@gmail.com"

COPY ./app /usr/app
COPY ./conf /etc/php7/php-fpm.d/

RUN chmod -R 755 /usr/app
RUN chmod -R 644 /usr/app/wp-admin/index.php
RUN chmod -R 640 /usr/app/wp-config.php

WORKDIR /usr/app
